development:
  adapter: postgresql
  database: track_my_campaign_development
  host: localhost

test: &test
  adapter: postgresql
  database: track_my_campaign_test
  host: localhost

production:
  adapter: postgresql
  database: track_my_campaign_production
  pool: 5
  timeout: 5000