require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CityDesignationsController do

  # This should return the minimal set of attributes required to create a valid
  # CityDesignation. As you add validations to CityDesignation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "database_instance_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CityDesignationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all city_designations as @city_designations" do
      city_designation = CityDesignation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:city_designations).should eq([city_designation])
    end
  end

  describe "GET show" do
    it "assigns the requested city_designation as @city_designation" do
      city_designation = CityDesignation.create! valid_attributes
      get :show, {:id => city_designation.to_param}, valid_session
      assigns(:city_designation).should eq(city_designation)
    end
  end

  describe "GET new" do
    it "assigns a new city_designation as @city_designation" do
      get :new, {}, valid_session
      assigns(:city_designation).should be_a_new(CityDesignation)
    end
  end

  describe "GET edit" do
    it "assigns the requested city_designation as @city_designation" do
      city_designation = CityDesignation.create! valid_attributes
      get :edit, {:id => city_designation.to_param}, valid_session
      assigns(:city_designation).should eq(city_designation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CityDesignation" do
        expect {
          post :create, {:city_designation => valid_attributes}, valid_session
        }.to change(CityDesignation, :count).by(1)
      end

      it "assigns a newly created city_designation as @city_designation" do
        post :create, {:city_designation => valid_attributes}, valid_session
        assigns(:city_designation).should be_a(CityDesignation)
        assigns(:city_designation).should be_persisted
      end

      it "redirects to the created city_designation" do
        post :create, {:city_designation => valid_attributes}, valid_session
        response.should redirect_to(CityDesignation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved city_designation as @city_designation" do
        # Trigger the behavior that occurs when invalid params are submitted
        CityDesignation.any_instance.stub(:save).and_return(false)
        post :create, {:city_designation => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:city_designation).should be_a_new(CityDesignation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CityDesignation.any_instance.stub(:save).and_return(false)
        post :create, {:city_designation => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested city_designation" do
        city_designation = CityDesignation.create! valid_attributes
        # Assuming there are no other city_designations in the database, this
        # specifies that the CityDesignation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CityDesignation.any_instance.should_receive(:update).with({ "database_instance_id" => "1" })
        put :update, {:id => city_designation.to_param, :city_designation => { "database_instance_id" => "1" }}, valid_session
      end

      it "assigns the requested city_designation as @city_designation" do
        city_designation = CityDesignation.create! valid_attributes
        put :update, {:id => city_designation.to_param, :city_designation => valid_attributes}, valid_session
        assigns(:city_designation).should eq(city_designation)
      end

      it "redirects to the city_designation" do
        city_designation = CityDesignation.create! valid_attributes
        put :update, {:id => city_designation.to_param, :city_designation => valid_attributes}, valid_session
        response.should redirect_to(city_designation)
      end
    end

    describe "with invalid params" do
      it "assigns the city_designation as @city_designation" do
        city_designation = CityDesignation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CityDesignation.any_instance.stub(:save).and_return(false)
        put :update, {:id => city_designation.to_param, :city_designation => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:city_designation).should eq(city_designation)
      end

      it "re-renders the 'edit' template" do
        city_designation = CityDesignation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CityDesignation.any_instance.stub(:save).and_return(false)
        put :update, {:id => city_designation.to_param, :city_designation => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested city_designation" do
      city_designation = CityDesignation.create! valid_attributes
      expect {
        delete :destroy, {:id => city_designation.to_param}, valid_session
      }.to change(CityDesignation, :count).by(-1)
    end

    it "redirects to the city_designations list" do
      city_designation = CityDesignation.create! valid_attributes
      delete :destroy, {:id => city_designation.to_param}, valid_session
      response.should redirect_to(city_designations_url)
    end
  end

end
