require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommunicationsController do

  # This should return the minimal set of attributes required to create a valid
  # Communication. As you add validations to Communication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "database_instance_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommunicationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all communications as @communications" do
      communication = Communication.create! valid_attributes
      get :index, {}, valid_session
      assigns(:communications).should eq([communication])
    end
  end

  describe "GET show" do
    it "assigns the requested communication as @communication" do
      communication = Communication.create! valid_attributes
      get :show, {:id => communication.to_param}, valid_session
      assigns(:communication).should eq(communication)
    end
  end

  describe "GET new" do
    it "assigns a new communication as @communication" do
      get :new, {}, valid_session
      assigns(:communication).should be_a_new(Communication)
    end
  end

  describe "GET edit" do
    it "assigns the requested communication as @communication" do
      communication = Communication.create! valid_attributes
      get :edit, {:id => communication.to_param}, valid_session
      assigns(:communication).should eq(communication)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Communication" do
        expect {
          post :create, {:communication => valid_attributes}, valid_session
        }.to change(Communication, :count).by(1)
      end

      it "assigns a newly created communication as @communication" do
        post :create, {:communication => valid_attributes}, valid_session
        assigns(:communication).should be_a(Communication)
        assigns(:communication).should be_persisted
      end

      it "redirects to the created communication" do
        post :create, {:communication => valid_attributes}, valid_session
        response.should redirect_to(Communication.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved communication as @communication" do
        # Trigger the behavior that occurs when invalid params are submitted
        Communication.any_instance.stub(:save).and_return(false)
        post :create, {:communication => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:communication).should be_a_new(Communication)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Communication.any_instance.stub(:save).and_return(false)
        post :create, {:communication => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested communication" do
        communication = Communication.create! valid_attributes
        # Assuming there are no other communications in the database, this
        # specifies that the Communication created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Communication.any_instance.should_receive(:update).with({ "database_instance_id" => "1" })
        put :update, {:id => communication.to_param, :communication => { "database_instance_id" => "1" }}, valid_session
      end

      it "assigns the requested communication as @communication" do
        communication = Communication.create! valid_attributes
        put :update, {:id => communication.to_param, :communication => valid_attributes}, valid_session
        assigns(:communication).should eq(communication)
      end

      it "redirects to the communication" do
        communication = Communication.create! valid_attributes
        put :update, {:id => communication.to_param, :communication => valid_attributes}, valid_session
        response.should redirect_to(communication)
      end
    end

    describe "with invalid params" do
      it "assigns the communication as @communication" do
        communication = Communication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Communication.any_instance.stub(:save).and_return(false)
        put :update, {:id => communication.to_param, :communication => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:communication).should eq(communication)
      end

      it "re-renders the 'edit' template" do
        communication = Communication.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Communication.any_instance.stub(:save).and_return(false)
        put :update, {:id => communication.to_param, :communication => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested communication" do
      communication = Communication.create! valid_attributes
      expect {
        delete :destroy, {:id => communication.to_param}, valid_session
      }.to change(Communication, :count).by(-1)
    end

    it "redirects to the communications list" do
      communication = Communication.create! valid_attributes
      delete :destroy, {:id => communication.to_param}, valid_session
      response.should redirect_to(communications_url)
    end
  end

end
