require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatabaseInstancesController do

  # This should return the minimal set of attributes required to create a valid
  # DatabaseInstance. As you add validations to DatabaseInstance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "organization_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatabaseInstancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all database_instances as @database_instances" do
      database_instance = DatabaseInstance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:database_instances).should eq([database_instance])
    end
  end

  describe "GET show" do
    it "assigns the requested database_instance as @database_instance" do
      database_instance = DatabaseInstance.create! valid_attributes
      get :show, {:id => database_instance.to_param}, valid_session
      assigns(:database_instance).should eq(database_instance)
    end
  end

  describe "GET new" do
    it "assigns a new database_instance as @database_instance" do
      get :new, {}, valid_session
      assigns(:database_instance).should be_a_new(DatabaseInstance)
    end
  end

  describe "GET edit" do
    it "assigns the requested database_instance as @database_instance" do
      database_instance = DatabaseInstance.create! valid_attributes
      get :edit, {:id => database_instance.to_param}, valid_session
      assigns(:database_instance).should eq(database_instance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DatabaseInstance" do
        expect {
          post :create, {:database_instance => valid_attributes}, valid_session
        }.to change(DatabaseInstance, :count).by(1)
      end

      it "assigns a newly created database_instance as @database_instance" do
        post :create, {:database_instance => valid_attributes}, valid_session
        assigns(:database_instance).should be_a(DatabaseInstance)
        assigns(:database_instance).should be_persisted
      end

      it "redirects to the created database_instance" do
        post :create, {:database_instance => valid_attributes}, valid_session
        response.should redirect_to(DatabaseInstance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved database_instance as @database_instance" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseInstance.any_instance.stub(:save).and_return(false)
        post :create, {:database_instance => { "organization_id" => "invalid value" }}, valid_session
        assigns(:database_instance).should be_a_new(DatabaseInstance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseInstance.any_instance.stub(:save).and_return(false)
        post :create, {:database_instance => { "organization_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested database_instance" do
        database_instance = DatabaseInstance.create! valid_attributes
        # Assuming there are no other database_instances in the database, this
        # specifies that the DatabaseInstance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DatabaseInstance.any_instance.should_receive(:update).with({ "organization_id" => "1" })
        put :update, {:id => database_instance.to_param, :database_instance => { "organization_id" => "1" }}, valid_session
      end

      it "assigns the requested database_instance as @database_instance" do
        database_instance = DatabaseInstance.create! valid_attributes
        put :update, {:id => database_instance.to_param, :database_instance => valid_attributes}, valid_session
        assigns(:database_instance).should eq(database_instance)
      end

      it "redirects to the database_instance" do
        database_instance = DatabaseInstance.create! valid_attributes
        put :update, {:id => database_instance.to_param, :database_instance => valid_attributes}, valid_session
        response.should redirect_to(database_instance)
      end
    end

    describe "with invalid params" do
      it "assigns the database_instance as @database_instance" do
        database_instance = DatabaseInstance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseInstance.any_instance.stub(:save).and_return(false)
        put :update, {:id => database_instance.to_param, :database_instance => { "organization_id" => "invalid value" }}, valid_session
        assigns(:database_instance).should eq(database_instance)
      end

      it "re-renders the 'edit' template" do
        database_instance = DatabaseInstance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatabaseInstance.any_instance.stub(:save).and_return(false)
        put :update, {:id => database_instance.to_param, :database_instance => { "organization_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested database_instance" do
      database_instance = DatabaseInstance.create! valid_attributes
      expect {
        delete :destroy, {:id => database_instance.to_param}, valid_session
      }.to change(DatabaseInstance, :count).by(-1)
    end

    it "redirects to the database_instances list" do
      database_instance = DatabaseInstance.create! valid_attributes
      delete :destroy, {:id => database_instance.to_param}, valid_session
      response.should redirect_to(database_instances_url)
    end
  end

end
