require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InterestLevelsController do

  # This should return the minimal set of attributes required to create a valid
  # InterestLevel. As you add validations to InterestLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "database_instance_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InterestLevelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all interest_levels as @interest_levels" do
      interest_level = InterestLevel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:interest_levels).should eq([interest_level])
    end
  end

  describe "GET show" do
    it "assigns the requested interest_level as @interest_level" do
      interest_level = InterestLevel.create! valid_attributes
      get :show, {:id => interest_level.to_param}, valid_session
      assigns(:interest_level).should eq(interest_level)
    end
  end

  describe "GET new" do
    it "assigns a new interest_level as @interest_level" do
      get :new, {}, valid_session
      assigns(:interest_level).should be_a_new(InterestLevel)
    end
  end

  describe "GET edit" do
    it "assigns the requested interest_level as @interest_level" do
      interest_level = InterestLevel.create! valid_attributes
      get :edit, {:id => interest_level.to_param}, valid_session
      assigns(:interest_level).should eq(interest_level)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InterestLevel" do
        expect {
          post :create, {:interest_level => valid_attributes}, valid_session
        }.to change(InterestLevel, :count).by(1)
      end

      it "assigns a newly created interest_level as @interest_level" do
        post :create, {:interest_level => valid_attributes}, valid_session
        assigns(:interest_level).should be_a(InterestLevel)
        assigns(:interest_level).should be_persisted
      end

      it "redirects to the created interest_level" do
        post :create, {:interest_level => valid_attributes}, valid_session
        response.should redirect_to(InterestLevel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interest_level as @interest_level" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterestLevel.any_instance.stub(:save).and_return(false)
        post :create, {:interest_level => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:interest_level).should be_a_new(InterestLevel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InterestLevel.any_instance.stub(:save).and_return(false)
        post :create, {:interest_level => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interest_level" do
        interest_level = InterestLevel.create! valid_attributes
        # Assuming there are no other interest_levels in the database, this
        # specifies that the InterestLevel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InterestLevel.any_instance.should_receive(:update).with({ "database_instance_id" => "1" })
        put :update, {:id => interest_level.to_param, :interest_level => { "database_instance_id" => "1" }}, valid_session
      end

      it "assigns the requested interest_level as @interest_level" do
        interest_level = InterestLevel.create! valid_attributes
        put :update, {:id => interest_level.to_param, :interest_level => valid_attributes}, valid_session
        assigns(:interest_level).should eq(interest_level)
      end

      it "redirects to the interest_level" do
        interest_level = InterestLevel.create! valid_attributes
        put :update, {:id => interest_level.to_param, :interest_level => valid_attributes}, valid_session
        response.should redirect_to(interest_level)
      end
    end

    describe "with invalid params" do
      it "assigns the interest_level as @interest_level" do
        interest_level = InterestLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterestLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => interest_level.to_param, :interest_level => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:interest_level).should eq(interest_level)
      end

      it "re-renders the 'edit' template" do
        interest_level = InterestLevel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InterestLevel.any_instance.stub(:save).and_return(false)
        put :update, {:id => interest_level.to_param, :interest_level => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interest_level" do
      interest_level = InterestLevel.create! valid_attributes
      expect {
        delete :destroy, {:id => interest_level.to_param}, valid_session
      }.to change(InterestLevel, :count).by(-1)
    end

    it "redirects to the interest_levels list" do
      interest_level = InterestLevel.create! valid_attributes
      delete :destroy, {:id => interest_level.to_param}, valid_session
      response.should redirect_to(interest_levels_url)
    end
  end

end
