require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MilestoneReachedsController do

  # This should return the minimal set of attributes required to create a valid
  # MilestoneReached. As you add validations to MilestoneReached, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "database_instance_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MilestoneReachedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all milestone_reacheds as @milestone_reacheds" do
      milestone_reached = MilestoneReached.create! valid_attributes
      get :index, {}, valid_session
      assigns(:milestone_reacheds).should eq([milestone_reached])
    end
  end

  describe "GET show" do
    it "assigns the requested milestone_reached as @milestone_reached" do
      milestone_reached = MilestoneReached.create! valid_attributes
      get :show, {:id => milestone_reached.to_param}, valid_session
      assigns(:milestone_reached).should eq(milestone_reached)
    end
  end

  describe "GET new" do
    it "assigns a new milestone_reached as @milestone_reached" do
      get :new, {}, valid_session
      assigns(:milestone_reached).should be_a_new(MilestoneReached)
    end
  end

  describe "GET edit" do
    it "assigns the requested milestone_reached as @milestone_reached" do
      milestone_reached = MilestoneReached.create! valid_attributes
      get :edit, {:id => milestone_reached.to_param}, valid_session
      assigns(:milestone_reached).should eq(milestone_reached)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MilestoneReached" do
        expect {
          post :create, {:milestone_reached => valid_attributes}, valid_session
        }.to change(MilestoneReached, :count).by(1)
      end

      it "assigns a newly created milestone_reached as @milestone_reached" do
        post :create, {:milestone_reached => valid_attributes}, valid_session
        assigns(:milestone_reached).should be_a(MilestoneReached)
        assigns(:milestone_reached).should be_persisted
      end

      it "redirects to the created milestone_reached" do
        post :create, {:milestone_reached => valid_attributes}, valid_session
        response.should redirect_to(MilestoneReached.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved milestone_reached as @milestone_reached" do
        # Trigger the behavior that occurs when invalid params are submitted
        MilestoneReached.any_instance.stub(:save).and_return(false)
        post :create, {:milestone_reached => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:milestone_reached).should be_a_new(MilestoneReached)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MilestoneReached.any_instance.stub(:save).and_return(false)
        post :create, {:milestone_reached => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested milestone_reached" do
        milestone_reached = MilestoneReached.create! valid_attributes
        # Assuming there are no other milestone_reacheds in the database, this
        # specifies that the MilestoneReached created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MilestoneReached.any_instance.should_receive(:update).with({ "database_instance_id" => "1" })
        put :update, {:id => milestone_reached.to_param, :milestone_reached => { "database_instance_id" => "1" }}, valid_session
      end

      it "assigns the requested milestone_reached as @milestone_reached" do
        milestone_reached = MilestoneReached.create! valid_attributes
        put :update, {:id => milestone_reached.to_param, :milestone_reached => valid_attributes}, valid_session
        assigns(:milestone_reached).should eq(milestone_reached)
      end

      it "redirects to the milestone_reached" do
        milestone_reached = MilestoneReached.create! valid_attributes
        put :update, {:id => milestone_reached.to_param, :milestone_reached => valid_attributes}, valid_session
        response.should redirect_to(milestone_reached)
      end
    end

    describe "with invalid params" do
      it "assigns the milestone_reached as @milestone_reached" do
        milestone_reached = MilestoneReached.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MilestoneReached.any_instance.stub(:save).and_return(false)
        put :update, {:id => milestone_reached.to_param, :milestone_reached => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:milestone_reached).should eq(milestone_reached)
      end

      it "re-renders the 'edit' template" do
        milestone_reached = MilestoneReached.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MilestoneReached.any_instance.stub(:save).and_return(false)
        put :update, {:id => milestone_reached.to_param, :milestone_reached => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested milestone_reached" do
      milestone_reached = MilestoneReached.create! valid_attributes
      expect {
        delete :destroy, {:id => milestone_reached.to_param}, valid_session
      }.to change(MilestoneReached, :count).by(-1)
    end

    it "redirects to the milestone_reacheds list" do
      milestone_reached = MilestoneReached.create! valid_attributes
      delete :destroy, {:id => milestone_reached.to_param}, valid_session
      response.should redirect_to(milestone_reacheds_url)
    end
  end

end
