require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PositionTypesController do

  # This should return the minimal set of attributes required to create a valid
  # PositionType. As you add validations to PositionType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "database_instance_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PositionTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all position_types as @position_types" do
      position_type = PositionType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:position_types).should eq([position_type])
    end
  end

  describe "GET show" do
    it "assigns the requested position_type as @position_type" do
      position_type = PositionType.create! valid_attributes
      get :show, {:id => position_type.to_param}, valid_session
      assigns(:position_type).should eq(position_type)
    end
  end

  describe "GET new" do
    it "assigns a new position_type as @position_type" do
      get :new, {}, valid_session
      assigns(:position_type).should be_a_new(PositionType)
    end
  end

  describe "GET edit" do
    it "assigns the requested position_type as @position_type" do
      position_type = PositionType.create! valid_attributes
      get :edit, {:id => position_type.to_param}, valid_session
      assigns(:position_type).should eq(position_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PositionType" do
        expect {
          post :create, {:position_type => valid_attributes}, valid_session
        }.to change(PositionType, :count).by(1)
      end

      it "assigns a newly created position_type as @position_type" do
        post :create, {:position_type => valid_attributes}, valid_session
        assigns(:position_type).should be_a(PositionType)
        assigns(:position_type).should be_persisted
      end

      it "redirects to the created position_type" do
        post :create, {:position_type => valid_attributes}, valid_session
        response.should redirect_to(PositionType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved position_type as @position_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PositionType.any_instance.stub(:save).and_return(false)
        post :create, {:position_type => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:position_type).should be_a_new(PositionType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PositionType.any_instance.stub(:save).and_return(false)
        post :create, {:position_type => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested position_type" do
        position_type = PositionType.create! valid_attributes
        # Assuming there are no other position_types in the database, this
        # specifies that the PositionType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PositionType.any_instance.should_receive(:update).with({ "database_instance_id" => "" })
        put :update, {:id => position_type.to_param, :position_type => { "database_instance_id" => "" }}, valid_session
      end

      it "assigns the requested position_type as @position_type" do
        position_type = PositionType.create! valid_attributes
        put :update, {:id => position_type.to_param, :position_type => valid_attributes}, valid_session
        assigns(:position_type).should eq(position_type)
      end

      it "redirects to the position_type" do
        position_type = PositionType.create! valid_attributes
        put :update, {:id => position_type.to_param, :position_type => valid_attributes}, valid_session
        response.should redirect_to(position_type)
      end
    end

    describe "with invalid params" do
      it "assigns the position_type as @position_type" do
        position_type = PositionType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PositionType.any_instance.stub(:save).and_return(false)
        put :update, {:id => position_type.to_param, :position_type => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:position_type).should eq(position_type)
      end

      it "re-renders the 'edit' template" do
        position_type = PositionType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PositionType.any_instance.stub(:save).and_return(false)
        put :update, {:id => position_type.to_param, :position_type => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested position_type" do
      position_type = PositionType.create! valid_attributes
      expect {
        delete :destroy, {:id => position_type.to_param}, valid_session
      }.to change(PositionType, :count).by(-1)
    end

    it "redirects to the position_types list" do
      position_type = PositionType.create! valid_attributes
      delete :destroy, {:id => position_type.to_param}, valid_session
      response.should redirect_to(position_types_url)
    end
  end

end
