require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SurveyEmailSentsController do

  # This should return the minimal set of attributes required to create a valid
  # SurveyEmailSent. As you add validations to SurveyEmailSent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "database_instance_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurveyEmailSentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all survey_email_sents as @survey_email_sents" do
      survey_email_sent = SurveyEmailSent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:survey_email_sents).should eq([survey_email_sent])
    end
  end

  describe "GET show" do
    it "assigns the requested survey_email_sent as @survey_email_sent" do
      survey_email_sent = SurveyEmailSent.create! valid_attributes
      get :show, {:id => survey_email_sent.to_param}, valid_session
      assigns(:survey_email_sent).should eq(survey_email_sent)
    end
  end

  describe "GET new" do
    it "assigns a new survey_email_sent as @survey_email_sent" do
      get :new, {}, valid_session
      assigns(:survey_email_sent).should be_a_new(SurveyEmailSent)
    end
  end

  describe "GET edit" do
    it "assigns the requested survey_email_sent as @survey_email_sent" do
      survey_email_sent = SurveyEmailSent.create! valid_attributes
      get :edit, {:id => survey_email_sent.to_param}, valid_session
      assigns(:survey_email_sent).should eq(survey_email_sent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SurveyEmailSent" do
        expect {
          post :create, {:survey_email_sent => valid_attributes}, valid_session
        }.to change(SurveyEmailSent, :count).by(1)
      end

      it "assigns a newly created survey_email_sent as @survey_email_sent" do
        post :create, {:survey_email_sent => valid_attributes}, valid_session
        assigns(:survey_email_sent).should be_a(SurveyEmailSent)
        assigns(:survey_email_sent).should be_persisted
      end

      it "redirects to the created survey_email_sent" do
        post :create, {:survey_email_sent => valid_attributes}, valid_session
        response.should redirect_to(SurveyEmailSent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved survey_email_sent as @survey_email_sent" do
        # Trigger the behavior that occurs when invalid params are submitted
        SurveyEmailSent.any_instance.stub(:save).and_return(false)
        post :create, {:survey_email_sent => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:survey_email_sent).should be_a_new(SurveyEmailSent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SurveyEmailSent.any_instance.stub(:save).and_return(false)
        post :create, {:survey_email_sent => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested survey_email_sent" do
        survey_email_sent = SurveyEmailSent.create! valid_attributes
        # Assuming there are no other survey_email_sents in the database, this
        # specifies that the SurveyEmailSent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SurveyEmailSent.any_instance.should_receive(:update).with({ "database_instance_id" => "1" })
        put :update, {:id => survey_email_sent.to_param, :survey_email_sent => { "database_instance_id" => "1" }}, valid_session
      end

      it "assigns the requested survey_email_sent as @survey_email_sent" do
        survey_email_sent = SurveyEmailSent.create! valid_attributes
        put :update, {:id => survey_email_sent.to_param, :survey_email_sent => valid_attributes}, valid_session
        assigns(:survey_email_sent).should eq(survey_email_sent)
      end

      it "redirects to the survey_email_sent" do
        survey_email_sent = SurveyEmailSent.create! valid_attributes
        put :update, {:id => survey_email_sent.to_param, :survey_email_sent => valid_attributes}, valid_session
        response.should redirect_to(survey_email_sent)
      end
    end

    describe "with invalid params" do
      it "assigns the survey_email_sent as @survey_email_sent" do
        survey_email_sent = SurveyEmailSent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SurveyEmailSent.any_instance.stub(:save).and_return(false)
        put :update, {:id => survey_email_sent.to_param, :survey_email_sent => { "database_instance_id" => "invalid value" }}, valid_session
        assigns(:survey_email_sent).should eq(survey_email_sent)
      end

      it "re-renders the 'edit' template" do
        survey_email_sent = SurveyEmailSent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SurveyEmailSent.any_instance.stub(:save).and_return(false)
        put :update, {:id => survey_email_sent.to_param, :survey_email_sent => { "database_instance_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested survey_email_sent" do
      survey_email_sent = SurveyEmailSent.create! valid_attributes
      expect {
        delete :destroy, {:id => survey_email_sent.to_param}, valid_session
      }.to change(SurveyEmailSent, :count).by(-1)
    end

    it "redirects to the survey_email_sents list" do
      survey_email_sent = SurveyEmailSent.create! valid_attributes
      delete :destroy, {:id => survey_email_sent.to_param}, valid_session
      response.should redirect_to(survey_email_sents_url)
    end
  end

end
